default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: tzolkin
  password: D3s4rr0ll0

development:
  <<: *default
  database: surveyor_development

test:
  <<: *default
  database: surveyor_test
